name: test_pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install packages
        run: |
          python -m pip install --upgrage pip
          python install -r requirements.txt
      - name: run test
        run: |
          cd project
          pytest project/tests.py
